# config.yml

backend:
  name: github
  repo: MinghongGao/MinghongGao.github.io # Branch to update (optional; defaults to master)
media_folder: 'images/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }

